eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8767
spring:
  application:
    name: eureka-client1
##Feign ¿ªÆô¶ÏÂ·Æ÷
feign:
  hystrix:
    enabled: false